services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - merch
    networks:
      - merch_network


  merch:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: ${db_name}
    ports:
      - "5432:5432"
    volumes:
      - merch_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - merch_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  merch_data:

networks:
  merch_network:
    driver: bridge